"""
Physics-Trained Neural Wave Surrogate (src/wave_surrogate.py)
============================================================
Fast neural surrogate for the 116-node Gibbs-damped elastodynamic wave PDE solver.

Operational Rationale:
----------------------
The full transient finite-difference solver (src/rod_transient.py) requires
~300 ms per stroke to integrate 116 nodes over 8,194 subcycles. In real-time
model predictive control (MPC), evaluating 20-50 speed candidates at each cycle
would take 6-15 seconds, breaching edge PLC real-time deadlines (< 100 ms).

This surrogate is trained on high-fidelity solutions generated by the PDE solver
across the operational parameter envelope (SPM in [1.0, 6.0], Temp in [40, 120] C,
Water Cut in [0.05, 0.75], Fillage in [0.5, 1.0]). It provides instantaneous load
predictions in microseconds for the MPC optimizer.
"""

from __future__ import annotations

import math
import time
from dataclasses import dataclass
from typing import Dict, List, Sequence, Tuple, Union
import numpy as np


@dataclass
class WavePrediction:
    pprl_kn: float
    mprl_kn: float
    min_downhole_tension_kn: float
    mean_downhole_tension_kn: float
    downhole_stroke_m: float
    inference_time_ms: float


class NeuralWaveSurrogate:
    """
    Two-layer MLP surrogate predicting dynamic rod-string loads from operational parameters.
    Input: [spm, temp_c, water_cut, pump_fillage]
    Output: [pprl_kn, mprl_kn, min_downhole_tension_kn, mean_downhole_tension_kn, downhole_stroke_m]
    """

    def __init__(
        self,
        weights_h1: np.ndarray | None = None,
        bias_h1: np.ndarray | None = None,
        weights_h2: np.ndarray | None = None,
        bias_h2: np.ndarray | None = None,
        weights_out: np.ndarray | None = None,
        bias_out: np.ndarray | None = None,
        x_mean: np.ndarray | None = None,
        x_std: np.ndarray | None = None,
        y_mean: np.ndarray | None = None,
        y_std: np.ndarray | None = None,
    ):
        self.d_in = 4
        self.d_h1 = 32
        self.d_h2 = 32
        self.d_out = 5

        # Normalization defaults
        self.x_mean = np.array([3.5, 80.0, 0.40, 0.90], dtype=np.float64) if x_mean is None else np.copy(x_mean)
        self.x_std = np.array([1.5, 25.0, 0.20, 0.15], dtype=np.float64) if x_std is None else np.copy(x_std)
        self.y_mean = np.array([75.0, 22.0, 5.0, 18.0, 3.2], dtype=np.float64) if y_mean is None else np.copy(y_mean)
        self.y_std = np.array([15.0, 8.0, 8.0, 6.0, 0.3], dtype=np.float64) if y_std is None else np.copy(y_std)

        # Initialize or set weights
        rng = np.random.RandomState(42)
        if weights_h1 is None:
            # He / Glorot initialization
            self.w1 = rng.randn(self.d_in, self.d_h1) * np.sqrt(2.0 / self.d_in)
            self.b1 = np.zeros(self.d_h1, dtype=np.float64)
            self.w2 = rng.randn(self.d_h1, self.d_h2) * np.sqrt(2.0 / self.d_h1)
            self.b2 = np.zeros(self.d_h2, dtype=np.float64)
            self.w3 = rng.randn(self.d_h2, self.d_out) * np.sqrt(2.0 / self.d_h2)
            self.b3 = np.zeros(self.d_out, dtype=np.float64)
        else:
            self.w1 = np.copy(weights_h1)
            self.b1 = np.copy(bias_h1)
            self.w2 = np.copy(weights_h2)
            self.b2 = np.copy(bias_h2)
            self.w3 = np.copy(weights_out)
            self.b3 = np.copy(bias_out)

    @staticmethod
    def _relu(x: np.ndarray) -> np.ndarray:
        return np.maximum(0.0, x)

    def predict(
        self,
        spm: float,
        temp_c: float,
        water_cut: float = 0.35,
        pump_fillage: float = 0.95,
    ) -> WavePrediction:
        t0 = time.perf_counter()
        x = np.array([spm, temp_c, water_cut, pump_fillage], dtype=np.float64)
        x_norm = (x - self.x_mean) / self.x_std

        # Layer 1
        h1 = self._relu(np.dot(x_norm, self.w1) + self.b1)
        # Layer 2
        h2 = self._relu(np.dot(h1, self.w2) + self.b2)
        # Output
        y_norm = np.dot(h2, self.w3) + self.b3
        y = y_norm * self.y_std + self.y_mean

        dt_ms = (time.perf_counter() - t0) * 1000.0

        return WavePrediction(
            pprl_kn=float(y[0]),
            mprl_kn=float(y[1]),
            min_downhole_tension_kn=float(y[2]),
            mean_downhole_tension_kn=float(y[3]),
            downhole_stroke_m=float(y[4]),
            inference_time_ms=dt_ms,
        )

    def train_on_data(
        self,
        X: np.ndarray,
        Y: np.ndarray,
        epochs: int = 400,
        lr: float = 0.005,
        weight_decay: float = 1e-4,
    ) -> Dict[str, float]:
        """
        Trains the neural surrogate on dataset (X, Y) via Mini-batch Adam / SGD.
        X: shape (N, 4)
        Y: shape (N, 5)
        """
        N = len(X)
        self.x_mean = np.mean(X, axis=0)
        self.x_std = np.std(X, axis=0) + 1e-6
        self.y_mean = np.mean(Y, axis=0)
        self.y_std = np.std(Y, axis=0) + 1e-6

        X_norm = (X - self.x_mean) / self.x_std
        Y_norm = (Y - self.y_mean) / self.y_std

        # Adam optimizer state
        m_w1, v_w1 = np.zeros_like(self.w1), np.zeros_like(self.w1)
        m_b1, v_b1 = np.zeros_like(self.b1), np.zeros_like(self.b1)
        m_w2, v_w2 = np.zeros_like(self.w2), np.zeros_like(self.w2)
        m_b2, v_b2 = np.zeros_like(self.b2), np.zeros_like(self.b2)
        m_w3, v_w3 = np.zeros_like(self.w3), np.zeros_like(self.w3)
        m_b3, v_b3 = np.zeros_like(self.b3), np.zeros_like(self.b3)

        beta1, beta2, eps = 0.9, 0.999, 1e-8

        for epoch in range(1, epochs + 1):
            # Forward
            z1 = np.dot(X_norm, self.w1) + self.b1
            h1 = self._relu(z1)
            z2 = np.dot(h1, self.w2) + self.b2
            h2 = self._relu(z2)
            y_pred = np.dot(h2, self.w3) + self.b3

            # Loss: MSE
            diff = y_pred - Y_norm
            loss = np.mean(diff ** 2)

            # Backpropagation
            grad_y = (2.0 / N) * diff
            grad_w3 = np.dot(h2.T, grad_y) + weight_decay * self.w3
            grad_b3 = np.sum(grad_y, axis=0)

            grad_h2 = np.dot(grad_y, self.w3.T)
            grad_z2 = grad_h2 * (z2 > 0)
            grad_w2 = np.dot(h1.T, grad_z2) + weight_decay * self.w2
            grad_b2 = np.sum(grad_z2, axis=0)

            grad_h1 = np.dot(grad_z2, self.w2.T)
            grad_z1 = grad_h1 * (z1 > 0)
            grad_w1 = np.dot(X_norm.T, grad_z1) + weight_decay * self.w1
            grad_b1 = np.sum(grad_z1, axis=0)

            # Adam update
            for param, grad, m, v in [
                (self.w1, grad_w1, m_w1, v_w1), (self.b1, grad_b1, m_b1, v_b1),
                (self.w2, grad_w2, m_w2, v_w2), (self.b2, grad_b2, m_b2, v_b2),
                (self.w3, grad_w3, m_w3, v_w3), (self.b3, grad_b3, m_b3, v_b3),
            ]:
                m[:] = beta1 * m + (1.0 - beta1) * grad
                v[:] = beta2 * v + (1.0 - beta2) * (grad ** 2)
                m_hat = m / (1.0 - beta1 ** epoch)
                v_hat = v / (1.0 - beta2 ** epoch)
                param -= lr * m_hat / (np.sqrt(v_hat) + eps)

        final_loss = float(loss)
        return {"final_mse_norm": final_loss}
